import type { SimpleIcon } from "simple-icons";
import {
  siClaude,
  siCss,
  siCursor,
  siDocker,
  siFiles,
  siGit,
  siGithub,
  siGraphql,
  siHtml5,
  siJavascript,
  siMapbox,
  siMdx,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNodedotjs,
  siPostgresql,
  siReact,
  siRedis,
  siSass,
  siShadcnui,
  siSlickpic,
  siStackoverflow,
  siTailwindcss,
  siTypescript,
  siVite,
  siWagmi,
  siX,
} from "simple-icons";

const iconsBySlug: Record<string, SimpleIcon> = {
  react: siReact,
  typescript: siTypescript,
  javascript: siJavascript,
  html5: siHtml5,
  css3: siCss,
  css: siCss,
  claude: siClaude,
  cursor: siCursor,
  tailwindcss: siTailwindcss,
  nextdotjs: siNextdotjs,
  nodedotjs: siNodedotjs,
  graphql: siGraphql,
  git: siGit,
  docker: siDocker,
  mongodb: siMongodb,
  postgresql: siPostgresql,
  redis: siRedis,
  shadcnui: siShadcnui,
  wagmi: siWagmi,
  mysql: siMysql,
  vite: siVite,
  mdx: siMdx,
  mapbox: siMapbox,
  sass: siSass,
  scss: siSass,
};

const nameToSlug: Record<string, string> = {
  React: "react",
  TypeScript: "typescript",
  JavaScript: "javascript",
  WCAG: "wcag",
  HTML: "html5",
  HTML5: "html5",
  Claude: "claude",
  Cursor: "cursor",
  GPT: "openai",
  "Modern CSS": "css3",
  Tailwind: "tailwindcss",
  TailwindCSS: "tailwindcss",
  Shadcn: "shadcnui",
  "Next.js": "nextdotjs",
  "Node.js": "nodedotjs",
  GraphQL: "graphql",
  Git: "git",
  Docker: "docker",
  MongoDB: "mongodb",
  PostgreSQL: "postgresql",
  Redis: "redis",
  Wagmi: "wagmi",
  SQL: "mysql",
  Vite: "vite",
  MDX: "mdx",
  CSS: "css",
  SCSS: "sass",
  Mapbox: "mapbox",
};

export function getIconByName(name: string): SimpleIcon | undefined {
  const slug = nameToSlug[name] ?? name.toLowerCase().replace(/\s+/g, "");
  return iconsBySlug[slug];
}

export { siFiles, siGithub, siSlickpic, siStackoverflow, siX };
